apiVersion: v1
kind: ServiceAccount
metadata:
  name: inf-batch-job-dispatcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inf-batch-job-dispatcher-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inf-batch-job-dispatcher-binding
subjects:
- kind: ServiceAccount
  name: inf-batch-job-dispatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inf-batch-job-dispatcher-role
